### ISSUE TITLE
Some features cause errors for larger tolerances

### ISSUE THREAD

**Issue by AlisterH** [NRCan/geo_sim_processing#12]
Hi, trying out Reduce Bend I find that it works if I set the tolerance small enough, but when I increase the tolerance it starts erroring:
````
QGIS version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Reduce bend' starting…
Input parameters:
{ 'EXCLUDE_HOLE' : True, 'EXCLUDE_POLYGON' : True, 'INPUT' : 'S:/Jobs/2237 - Metlifecare - Clevedon/cad/GIS/contours.gpkg|layername=contours', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'SMOOTH' : True, 'TOLERANCE' : 3, 'VERBOSE' : False }

Start normalizing input layer
Results: {'OUTPUT': 'output_a125ca40_ed65_4c0e_ba73_9032729397d1'}
Results: {'OUTPUT': 'output_5dd31aec_fdbd_48a3_9e18_85762f706b7b'}
End normalizing input layer
Possibly non OGC simple feature at 424216.4075303071,786811.5 use Fix Geometries
Traceback (most recent call last):
File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo_sim_processing\reduce_bend_algorithm.py", line 208, in processAlgorithm
exclude_hole, validate_structure, feedback)
File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo_sim_processing\reduce_bend_algorithm.py", line 1182, in reduce
results = rb.reduce_bends()
File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo_sim_processing\reduce_bend_algorithm.py", line 1561, in reduce_bends
self._manage_reduce_bend()
File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo_sim_processing\reduce_bend_algorithm.py", line 1683, in _manage_reduce_bend
nbr_bend_detected = ReduceBend.detect_bends(rb_geom)
File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo_sim_processing\reduce_bend_algorithm.py", line 1358, in detect_bends
del orientation[0] # Do not process the first angle as it is the angle of the start/end
IndexError: list assignment index out of range

Execution failed after 55.74 seconds

Loading resulting layers
Algorithm 'Reduce bend' finished
````
It wasn't obvious to me if `Possibly non OGC simple feature at 424216.4075303071,786811.5 use Fix Geometries` means that there is a problem with the input file and I should run fix geometries on it before running reduce bend, or if that message is unrelated to the error and just means that the output might have invalid geometries and I should run fix geometries on the output.

Anyway, running fix geometries on the input didn't help with the error, so I tried zooming to the coordinates in the message - there were two very small features at approximately at that location so I deleted them both.  Rerunning Reduce Bend it errored with the same message, with different coordinates, so I zoomed to that location and deleted the feature there.  I was then able to run Reduce Bend successfully.  The features I deleted are shown below.

It seems unlikely there is something technically wrong with those features (but if there is I guess a ticket should be filed to improve Fix Geometries).  I'm guessing instead that these errors could be avoided with improvements to Reduce Bend (perhaps to just leave unmodified any features that can't be simplified?).  I guess such features could be deleted instead (perhaps by preprocessing with another tool), but I'm not sure if that is actually a good idea. 

This is the input layer, before and after deleting of the problematic features:
[inputs.zip](https://github.com/NRCan/geo_sim_processing/files/6347582/inputs.zip)

![image](https://user-images.githubusercontent.com/714600/115485527-090dbc80-a2a9-11eb-983e-bde2d793b71c.png)
![image](https://user-images.githubusercontent.com/714600/115485436-d663c400-a2a8-11eb-8d09-df4ae2402b07.png)

**Comment by Dan-Eli** [comment]
@AlisterH bug corrected in version 1.1.0 available in QGIS Plugin Repository

**Comment by Dan-Eli** [comment]
It was a _false positive_ detected with the message:
`Possibly non OGC simple feature at 424216.4075303071,786811.5 use Fix Geometries`
The geometry was good but very small.
There is no need to post an issue about Fix Geometries. 
More evaluation is needed if the comment should be removed or the epsilon near zero value should be adjusted (it's already supposed to be a dynamic value).  
There was another real bug that was corrected in Reduce Bend.

**Comment by Dan-Eli** [comment]
False positive error corrected
